<?php

namespace App\Services;

use App\Models\WorkPackage;
use Illuminate\Support\Str;

class HandoverGenerator
{
    public function generate(WorkPackage $package, int $userId): array
    {
        $project = $package->project;
        $now = now();

        $content = $this->buildMarkdown($package, $project, $userId);

        $branch = 'handover/' . Str::slug($package->name) . '-' . $now->format('YmdHis');

        return [
            'work_package_id' => $package->id,
            'generated_by' => $userId,
            'content' => $content,
            'pr_branch' => $branch,
            'pr_status' => 'draft',
            'generated_at' => $now,
        ];
    }

    private function buildMarkdown(WorkPackage $package, $project, int $userId): string
    {
        $lines = [];

        $lines[] = "# Handover Capsule: " . $package->name;
        $lines[] = "";
        $lines[] = "> Generated on " . now()->format('F j, Y \a\t g:i A');
        $lines[] = "";
        $lines[] = "---";
        $lines[] = "";

        $lines[] = "## Project Context";
        $lines[] = "";
        $lines[] = "- **Project:** " . $project->name;
        $lines[] = "- **Work Package:** " . $package->name;
        $lines[] = "- **Status:** " . str_replace('_', ' ', $package->status);
        $lines[] = $package->assignee ? "- **Assignee:** " . $package->assignee->name : "";
        $lines[] = $package->linked_branch ? "- **Linked Branch:** `" . $package->linked_branch . "`" : "";
        $lines[] = $package->planned_start ? "- **Planned Start:** " . $package->planned_start->format('M j, Y') : "";
        $lines[] = $package->planned_end ? "- **Planned End:** " . $package->planned_end->format('M j, Y') : "";
        $lines[] = "";

        if ($package->description) {
            $lines[] = "## Description";
            $lines[] = "";
            $lines[] = $package->description;
            $lines[] = "";
        }

        $lines[] = "## Key Decisions";
        $lines[] = "";
        $lines[] = "- *No decision log entries captured yet.*";
        $lines[] = "";

        $lines[] = "## Technical Notes";
        $lines[] = "";
        $lines[] = "- *No technical notes recorded.*";
        $lines[] = "";

        $lines[] = "## Open Questions";
        $lines[] = "";
        $lines[] = "- *None documented.*";
        $lines[] = "";

        $lines[] = "---";
        $lines[] = "";
        $lines[] = "_This capsule was auto-generated by Project Command Center._";

        return implode("\n", $lines);
    }
}
